### ISSUE TITLE
Assignment 1-1 - The Basics

### ISSUE THREAD

**Issue by gstark** [sakbar55/assignments#1]
## Week 1 - Assignment #1
- [ ] Read Mason's [Code School Manefesto](http://masondesu.github.io/code-school-manifesto/).
- [ ] Look over this [Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide). You don't need to commit it all to memory. You probably won't understand all of it; that's okay. Just skim it, know that it exists, bookmark it, and refer to it often as we move forward.
- [ ] Complete the just the exercises given below by copying the comments to a new file (name it `day_one.rb`) and placing your solution below each comment.
- [ ] Publish your completed exercises to a Github Gist
  - HINT: Use the same filename in the "Filename with extension" input box.
- [ ] Add the link to the Github Gist to a comment in this issue
- [ ] Close the issue to indicate you are complete
- **Bonus**
  - [ ] Clone the Gist you created to your computer.
  - [ ] Add the bonus exercises to your `day_one.rb` and attempt to complete them both.
  - [ ] Install `zsh` and `oh-my-zsh` and choose a theme of your liking. Take a screenshot of your terminal with the theme installed. Attach to the issue before closing.
  - [ ] Customize the color of your terminal background and font color. Take a screenshot of your terminal with your color selection. Attach to the issue before closing.
- [ ] Close this issue to notify me for review.

`day_one.rb`:

``` ruby
#1. Assign "Hello World" to a variable named message.

#2. Assign a different string to a different variable.

#3. Assign a number to a variable.

#4. Make an array of at least four of your favorite movies or books or bands.

#5. Make a hash of information about yourself with at least four key-value pairs.
```
### Bonus Exercises

``` ruby
#6. Use string interpolation to display the number from exercise 3 in the middle a string.

#7. Make an array of hashes containing more information about your favorite movies. The hashes should have at least three key value pairs.

#8. Use `each` to loop through the answer from exercise #7 and print only one property from the hash. i.e., given `{ title: "Gone with the Wind" }` you print "Gone with the Wind".
```
### Resources
- Creating gists - https://help.github.com/articles/creating-gists/
- Try out your code first in `irb`
- Ask questions. Talk to other students first, then come ask in pairs!

**Comment by sakbar55** [comment]
https://gist.github.com/sakbar55/cdae81afa332434b1181
