### ISSUE TITLE
Assignment 6-1 - Classes Review

### ISSUE THREAD

**Issue by gstark** [sakbar55/assignments#20]
If you haven't forked the `makes_perfect` repo, clone it into your own github account. (Use the `fork` feature on github.com)

[makes-perfect repo](https://github.com/tiy-tpa-ruby-q3-2015/makes-perfect)

Clone the repository to your computer (make sure you do the `git clone` in the top directory of where you keep your TIY work)

Follow the instructions in the `README.md` file in the `classes` folder.
# Explorer Mode

You should be writing all your code in the `classes.rb` file and _only_ removing `skip` statements from the tests in the `test_classes.rb` file.

When done, add, commit, and push your changes. Add a link to your forked repository as a comment and close the issue.

**Comment by sakbar55** [comment]
Did this several weeks ago and forgot to turn this in:
https://github.com/sakbar55/makes-perfect/tree/master/classes
