### ISSUE TITLE
Assignment 6-3 - Rails dictionary revisited

### ISSUE THREAD

**Issue by gstark** [sakbar55/assignments#22]
Tonight's homework is to extend the rails dictionary from last night's homework
# Explorer Mode
- [x] Continue editing your rails dictionary repo from last night
- [x] Add a field to indicate the type of word, e.g. `verb`, `noun`, `adjective`, `adverb`, etc.
- [x] Add a field to store an example of the word in use
- [x] If your app doesn't already have a search feature, add one.
  - [x] Make the search a partial search of the word.
  - [x] Decide if you are going to reuse the `index` action or if you are going to create your own action. Be prepared to discuss your choice between the two.
- [x] Commit your work before moving on to other modes below
- [x] If you didn't spruce up the dictionary from last night, add bootstrap to your app.
  - [x] Add a navigation bar
  - [x] Style the tables
  - [x] Style the forms
# Adventure Mode
- [ ] Make the search be a partial seach of the word _or_ definition (if your dictionary supports multiple definitions you can skip this step if you can't figure this out)
- [ ] Create a logo for your app and place the logo in the navigation bar
# Epic Mode
- [ ] Allow words to have _multiple_ examples of usage. NOTE: Explorer mode had you make the example directly on the definition, here you must undo that work to make them distinct and multiple.
  - [ ] Show all the examples on the _show_ page for the word
  - [ ] On the index page for words show how many examples each word has
  - [ ] The edit form for a word should have a link to a separate page where the user can _add an example_ for this word.
  - [ ] _examples_ should be a separate resource with it's own controller and views

**Comment by sakbar55** [comment]
Explorer mode complete!
https://github.com/sakbar55/railsdictionary
