### ISSUE TITLE
Assignment 8-4 - Refocusing on Design

### ISSUE THREAD

**Issue by gstark** [sakbar55/assignments#31]
While we shouldn't judge a book by its cover, it is well known that users will judge
a website by it's design. Design is critical in gaining a user base and making for a
pleasant experience for your customers.

For your final projects a great design will be critical. Even though we may have put blood, sweat, and tears into making a brilliantly implemented Rails app, what users (and prospective employers) and Demo Day guests will notice first is our design. So while we need to have well structured code we also need to have an eye for design.

This is often difficult for developers without design experience (it is very true for me!) So the more we practice, the better we will be. It will also make us appreciate the Front End and UI/UX members of our teams.
# Explorer Mode
- [x] Perfect the design of your Iron Topics app
- [x] Utilize Bootstrap to it's fullest
  - [x] Choose a great looking font
  - [x] Make your forms well positioned, sized, and structured.
  - [x] Provide hint or explaination text where appropriate.
  - [ ] Consider different UI elements when appropriate (e.g. drop-downs or a 'numeric' type for the interest level)
  - [x] Have things nicely aligned
  - [x] Focus on color choice, not everything in the app should be black text
  - [ ] Use Andi's design ideas from her talk. (e.g. larger inputs make apps seem _easier to use_)
- [ ] Create a landing page
  - [ ] Explain the purpose of the app, use a mixture of text and images.
  - [ ] Include The Iron Yard logo somewhere on the landing page. See our corporate [brand standards](http://theironyard.com/about/brand-standards/) for downloads of logos and rules for use. Adhere to them!
  - [ ] Get inspiration from some of your favorite apps for how they present their landing page
# Adventure Mode
- [ ] Show your app to several friends or family members (or Iron Yard staff...)
  - [ ] Ask them if they think the app is easy to use.
  - [ ] Get feedback on the design and ease of use.
  - [ ] Document their feedback in the issue comments for this assignment.
  - [ ] Make the changes you feel improve the app, document the commits that improve the design based on feedback.

**Comment by sakbar55** [comment]
https://github.com/sakbar55/irontopics
